<?php

/**
 * @file
 * Drupal hooks and functions for the acb module.
 *
 * @todo code cleanup.
 * @todo define services where appropriate.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\node\NodeInterface;
use Drupal\user\Entity\User;

/**
 * Implements hook_help().
 */
function acb_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the acb module.
    case 'help.page.acb':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The Drupal community has developed several excellent
      modules to get fine-grained access control over a node (e.g. Content Access,
      Domain Access, Workflow, Organic Groups, Taxonomy Access Control, ...)
      Whereas each of these modules provides access control based on a specific
      feature, they tend to break eachothers functionality if used together.') . '</p>';
      $output .= '<p>' . t('Access Control Bridge solves this by creating a working
      interplay between all enabled access control modules.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_modules_installed().
 */
function acb_modules_installed($modules) {
  // Check if newly enabled modules are access control modules.
  $new = count(array_intersect(acb_get_modules(TRUE), $modules));
  if ($new) {
    // Ask for rebuilding node permissions.
    node_access_needs_rebuild(TRUE);
  }
}

/**
 * Returns a list of all active access control modules.
 *
 * @param bool $self
 *   Boolean indicating if acb itself should be included in the list.
 *
 * @return array
 *   An array containing all active access controlling modules.
 */
function acb_get_modules($self = FALSE) {
  // Get implementations of node_grants.
  $implementations = [];
  /** @var \Drupal\Core\Extension\ModuleHandlerInterface $module_handler */
  $module_handler = \Drupal::moduleHandler();
  $module_handler->invokeAllWith(
    'node_grants',
    function (callable $hook, string $module) use (&$implementations) {
      $implementations[] = $module;
    }
  );
  // Get implementations of node_access_records.
  $module_handler->invokeAllWith(
    'node_access_records',
    function (callable $hook, string $module) use (&$implementations) {
      $implementations[] = $module;
    }
  );

  $modules = array_unique($implementations);

  // Exclude ACL as it doesn't control anything on its own.
  $exclude = ['acl'];
  if ($self) {
    $exclude[] = 'acb';
  }

  // Sort the list so the modules are always returned in the same order.
  sort($modules);
  return array_diff($modules, $exclude);
}

/**
 * Implements hook_node_access_records_alter().
 *
 * Creates and inserts our cascaded access records for nodes.
 */
function acb_node_access_records_alter(&$grants, NodeInterface $node) {
  // Split all grants into their respective controlling modules.
  $split_grants = [];
  foreach (acb_get_modules() as $module) {
    $grant_storage = [];
    foreach ($grants as $key => $grant) {
      switch ($grant['realm']) {
        // 'all' and ACL require special care.
        case 'acl':
        case 'all':
          // Check 'module' or '#module' key.
          // Assume Content Access if not present.
          if (isset($grant['module'])) {
            $realm = $grant['module'];
          }
          elseif (isset($grant['#module'])) {
            $realm = $grant['#module'];
          }
          else {
            $realm = 'content_access';
          }
          break;

        default:
          $realm = $grant['realm'];
          break;
      }

      if (acb_is_module_realm($realm, $module) === TRUE) {
        $grant_storage[$key] = $grant;
      }
    }
    $split_grants[$module] = $grant_storage;
  }

  // Filter out any modules that didn't set access records.
  $split_grants = array_filter($split_grants);

  // Only proceed and alter the grants if multiple modules control this node.
  // Otherwise, legacy user grants will control the node as usual.
  if (count($split_grants) <= 1) {
    return;
  }

  // Convert 'all' realm grants to anonymous and authenticated role grants.
  // @todo check if still needed in D8.
  $roles = [
    0 => AccountInterface::ANONYMOUS_ROLE,
    1 => AccountInterface::AUTHENTICATED_ROLE,
  ];
  foreach ($split_grants as $module => $split_grant_module) {
    foreach ($split_grant_module as $key => $split_grant) {
      if ($split_grant['realm'] == 'all') {
        foreach ($roles as $rid => $rolename) {
          $split_grants[$module][$rid] = $split_grant;
          $split_grants[$module][$rid]['realm'] = $module . '_rid';
          $split_grants[$module][$rid]['gid'] = $rid;
        }
        unset($split_grants[$module][$key]);
      }
    }
  }

  // @todo Find out if there is a reason to keep existing grants.
  // Currently we only assign the ACB grants, to enforce multiple access control
  // modules working together as expected.
  $grants = _acb_cascade_grants($split_grants, TRUE);
}

/**
 * Implements hook_node_grants_alter().
 *
 * Informs Drupal of the current user's grants.
 * Uses the _alter function to calculate our grants based on existing ones.
 */
function acb_node_grants_alter(&$grants, AccountInterface $account, $op) {
  // Split grants into their controlling modules
  // and prepare the array for recursion.
  $split_grants = [];

  // ACL handling requires module determination via database lookup.
  if (\Drupal::moduleHandler()->moduleExists('acl')) {
    $acl = \Drupal::database()->select('acl')
      ->fields('acl', ['acl_id', 'module'])
      ->execute()
      ->fetchAllAssoc('acl_id');
  }

  // For ACB grants, 'Edit any domain content' and
  // 'Delete any domain content' permissions must be enabled.
  // Enable other modules for effective control
  // (due to our implemented AND logic).
  // Add to user grants if Domain Access is active and not already present.
  // Fork $grants to avoid permanent addition to the referenced array.
  $acb_grants = $grants;
  if (\Drupal::moduleHandler()->moduleExists('domain_access') && ($op == 'update' || $op == 'delete')) {
    $user = User::load($account->id());
    $domains = \Drupal::service('domain_access.manager')->getAccessValues($user);
    if (!empty($domains)) {
      foreach ($domains as $id) {
        if (abs($id) > 0) {
          $value = ($id > 0) ? $id : 0;
          if (!isset($acb_grants['domain_id']) || !in_array($value, $acb_grants['domain_id'])) {
            $acb_grants['domain_id'][] = $value;
          }
        }
      }
    }
  }

  foreach (acb_get_modules() as $module) {
    // ACL requires special care. Extract the ACL ids for the current module.
    if (\Drupal::moduleHandler()->moduleExists('acl')) {
      $entry_storage = [];
      foreach ($acl as $key => $entry) {
        if (acb_is_module_realm($entry->module, $module) === TRUE) {
          $entry_storage[$key] = $entry;
        }
      }
      $acl_current = array_keys($entry_storage);
    }

    foreach ($acb_grants as $realm => $gids) {
      // ACL requires special care:
      // Filter out ACL entries not set by the current module.
      if ($realm == 'acl') {
        $gids = array_intersect($gids, $acl_current);
      }

      // Add group IDs if the realm is from
      // the current module or has ACL entries.
      if ((acb_is_module_realm($realm, $module) === TRUE) || ($realm == 'acl' && !empty($gids))) {
        // Eventually prepare the module's subarray for pushing.
        if (empty($split_grants[$module])) {
          $split_grants[$module] = [];
        }
        foreach ($gids as $gid) {
          array_push($split_grants[$module], ['realm' => $realm, 'gid' => $gid]);
        }
      }
    }
  }

  // We keep the existing grants and merge ACB's to
  // support the case where only one module controls the node.
  // Filter out any modules that didn't set grants.
  $grants = array_merge($grants, _acb_cascade_grants(array_filter($split_grants)));
}

/**
 * Checks if a realm is originating from a specified module.
 *
 * @param string $realm
 *   A string containing a realm machine_name.
 * @param string $module
 *   A module's machine name.
 *
 * @return bool
 *   TRUE if the specified realm originates from the given module,
 *   FALSE otherwise.
 */
function acb_is_module_realm($realm, $module) {
  // Just in case, ensure consistency.
  if ($module == 'domain_access') {
    $module = 'domain';
  }

  switch ($realm) {
    case 'term_access':
      return $module == 'taxonomy_access';

    default:
      return strpos($realm, $module) === 0;
  }
}

/**
 * Core function of this module: converts grants into cascaded grants.
 *
 * Converts split-sorted grants into cascaded grants.
 *
 * Handles both hook_node_grants_alter() and hook_node_access_records_alter().
 *
 * @param array $grants
 *   The recursive grants array.
 * @param bool $access_records
 *   (optional) Cascades access records (TRUE) or user grants (FALSE).
 * @param array $output
 *   (optional) Final output array used for recursion.
 * @param array $realm
 *   (optional) Realm storage array used for recursion.
 * @param bool $view
 *   (optional) Grant_view value used for recursion.
 * @param bool $update
 *   (optional) Grant_update value used for recursion.
 * @param bool $delete
 *   (optional) Grant_delete value used for recursion.
 *
 * @return array
 *   The output grants array.
 */
function _acb_cascade_grants($grants, $access_records = FALSE, &$output = [], $realm = [], $view = 1, $update = 1, $delete = 1) {
  // Respect the given element order of $grants for cross-combination.
  if (count($grants)) {
    // This nesting level has available combinations left.
    foreach (reset($grants) as $grant) {
      // Assemble new pieces for the realm.
      $realm_storage = $realm;
      $realm_storage[] = $grant['realm'] . '+' . $grant['gid'];
      // Try to go one level deeper.
      $grants_storage = array_slice($grants, 1);

      // Called recursively differently for node access records and user grants.
      if ($access_records) {
        // Simple math cascades each node access record grant:
        // multiplication retains zeros (deny),
        // allows one (allow) if all cascaded grants permit access.
        _acb_cascade_grants($grants_storage, $access_records, $output, $realm_storage, $view * $grant['grant_view'], $update * $grant['grant_update'], $delete * $grant['grant_delete']);
      }
      else {
        // For the user grants we call the recursive function twice:
        // Once using updated realm and once assuming the realm doesn't exist.
        _acb_cascade_grants($grants_storage, $access_records, $output, $realm);
        _acb_cascade_grants($grants_storage, $access_records, $output, $realm_storage);
      }
    }
  }

  // Create a record for this combination if:
  // - in case of access records: there are no remaining nesting levels
  // - in case of user grants: always!
  if (!count($grants) || !$access_records) {
    // Prepend 'acb' to comply to best practice of
    // prefixing realms with the name of their responsible module.
    $final_realm = 'acb&' . implode('&', $realm);
    // Finished combination; save it.
    // Exclude empty access record grants to save memory.
    if ($access_records && ($view || $update || $delete)) {
      // Node access record.
      $output[$final_realm] = [
        'realm' => $final_realm,
        'gid' => 0,
        'grant_view' => (int) $view,
        'grant_update' => (int) $update,
        'grant_delete' => (int) $delete,
        'priority' => 100,
      ];
    }
    elseif (!$access_records) {
      // User grant.
      if (!empty($realm)) {
        $output[$final_realm] = [0];
      }
    }
  }

  return $output;
}
