/**
 * Types for docs/headless/intake-blueprint.json.
 *
 * The blueprint is generated by tools/export_intake_blueprint.php from the
 * design file plus live Drupal field values, and is the single source of
 * truth for the intake UI. Nothing here may be hand-edited to "fix" the UI;
 * change the generator or the Drupal form instead.
 */

export const WIDGETS = [
  "text",
  "email",
  "tel",
  "date",
  "number",
  "select",
  "textarea",
  "radio",
  "checkbox-grid",
  "repeatable",
  "static",
  "consent",
  "checkbox",
] as const;

export type Widget = (typeof WIDGETS)[number];

/** Widgets the patient actually fills in and that get submitted. */
export const INPUT_WIDGETS: readonly Widget[] = [
  "text",
  "email",
  "tel",
  "date",
  "number",
  "select",
  "textarea",
  "radio",
  "checkbox-grid",
  "repeatable",
  "consent",
  "checkbox",
];

export interface FieldOption {
  value: string;
  label: string;
}

export type VisibleWhenOp = "eq" | "neq" | "notEmpty";

export interface VisibleWhen {
  /** Blueprint field name, i.e. the same string as {@link BlueprintField.name}. */
  field: string;
  op: VisibleWhenOp;
  value?: string;
}

export type SubmitTransform = "joinNewline";

export interface BlueprintField {
  /** The form input name to POST. Unique across the whole form. */
  name: string;
  /** The Drupal field to write. Several inputs may share one field via `part`. */
  drupalField: string;
  /** Address sub-component, or `first`/`second` for a multi-part string field. */
  part: string | null;
  widget: Widget;
  label: string;
  required: boolean;
  /** Render at half width in the two-column grid. */
  half: boolean;
  options: FieldOption[];
  default: string | null;
  description: string;
  placeholder: string;
  drupalType: string;
  /** Lower/upper bound exported from the Drupal field settings (integer/decimal). */
  min?: number;
  max?: number;
  /** Max character count exported from Drupal string/email/telephone settings. */
  maxLength?: number;
  /** Unit label rendered after a number input, e.g. `lbs`. */
  suffix?: string;
  /** Legal text; `static` fields only. */
  text?: string;
  /** Which config key supplied `text`. */
  textSource?: string;
  /** EPP tokens still present in `text`; must be resolved before display. */
  unresolvedTokens?: string[];
  submitTransform?: SubmitTransform;
  visibleWhen?: VisibleWhen[];
}

export interface BlueprintStep {
  id: string;
  title: string;
  subtitle: string;
  fields: BlueprintField[];
}

export interface Blueprint {
  form: string;
  generated: string;
  source: string;
  /** Count of distinct Drupal fields. Layout inputs may exceed this. */
  fieldCount: number;
  steps: BlueprintStep[];
}
